services:
  imdb_db:
    container_name: imdb_db
    image: postgres:17-alpine
    volumes:
      - imdb_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=imdbdb
      - POSTGRES_USER=imdb_user
      - POSTGRES_DB=imdb_db
    networks:
      imdb:

  imdb_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SRC_DIR: api
    container_name: imdb_api
    image: imdb_api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      imdb:
    depends_on:
      imdb_db

  imdb_cli:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SRC_DIR: cli
    container_name: imdb_cli
    image: imdb_cli
    networks:
      - imdb
    depends_on:
      - imdb_api
    stdin_open: true
    tty: true

  imdb_ingestion:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SRC_DIR: ingestion
    image: imdb_ingestion
    profiles:
      - build-only

networks:
  imdb:
    name: imdb
    external: true